config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources "entries"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
	mount_uploader :image, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params["id"])
  end

  def create 
  	entry_params = params["entry"].permit("title", "contents")
    entry = Entry.create(entry_params)
    redirect_to(entry_path(entry), notice: "New entry created")
  end
  def edit
    @entry = Entry.find(params["id"]) 
  end

  def update
  entry_params = params["entry"].permit("title", "contents","image")
  entry = Entry.find(params["id"])
  entry.update(entry_params)
  redirect_to(entry_path(entry), notice:"Entry updated")
  end

  def destroy
  @entry = Entry.find(params["id"])
  @entry.destroy
  redirect_to(entries_path, notice: "Entry deleted") 
  	
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.file_field :image %></p>
  <p><%= form.submit %></p>

<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<h1>My Rails Girls Diary</h1>
 
 <%= notice %>
 
 <%= link_to("New entry", new_entry_path) %> 

<% for entry in @entries %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
    <p><%= entry.date %></p>
    <p><%= truncate entry.contents %></p>
<% end %>


     

  
  <img src="http://railsgirls.com/images/rg-warsaw.png" />

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<%= notice %>
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Back to all entries", entries_path) %></p>
  <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
  <p><%= link_to("Delete this entry", @entry,method: :delete, data: {confirm: "Are you sure, dude?"}) %></p>
  <%= image_tag(@entry.image_url, width: 600) if @entry.image.present? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
           <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
               </button>
      <a class="navbar-brand" href="/">The Diary</a>
            </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to("Entries", entries_path) %></li>
      </ul>
              </div>
           </div>
      </nav>
      <div class="container">
        <%= yield %>
      </div>
  
      <footer>
  <div class="container">
    Rails Girls 2016
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>My Rails Girls Diary</h1>
  
  
<% for entry in @entries %>
  <h2><%= entry.title %></h2>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
<% end %>
     

  
  <img src="http://railsgirls.com/images/rg-warsaw.png" />